## 获取和修改像素点值

In [2]:
import cv2

img = cv2.imread('test.jpg')

In [3]:
px = img[100, 90]
print(px)

[242 202 183]


In [4]:
px_blue = img[100, 90, 0]
print(px_blue)

242


In [5]:
img[100, 90] = [255, 255, 255]
print(img[100, 90])

[255 255 255]


In [6]:
print(img.shape) # 行数，列数，通道数

(3932, 1749, 3)


In [7]:
print(img.dtype)

uint8


## ROI感兴趣区域

In [8]:
# 截取脸部ROI
face = img[100: 200, 115: 188]
cv2.imshow('face', face)
cv2.waitKey(0)

-1

## 通道的分割与合并

彩色图的BGR三个通道是可以分开单独访问的，也可以将单独的三个通道合并成一副图像
分别使用cv2.split, cv2.merge

In [9]:
b, g, r = cv2.split(img)
print(b)

[[243 243 244 ... 232 227 154]
 [243 244 244 ... 232 229 154]
 [243 243 243 ... 234 229 154]
 ...
 [206 206 206 ... 216 211 140]
 [203 203 203 ... 219 212 146]
 [151 151 151 ... 164 161 104]]


In [11]:
# 由于split()函数效率低，更高效的方式是用numpy中的索引
b = img[:, :, 0]
cv2.imwrite('test_blue.jpg', b)
cv2.imshow('blue', b)
cv2.waitKey(0)

-1